version: '3.8'

services:
  file-server:
    image: nginx:alpine
    container_name: file-server
    restart: unless-stopped
    volumes:
      - /root/files:/usr/share/nginx/html:ro
    networks:
      - n8n_with_https_default
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
    command: >
      sh -c "echo 'server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;
        
        location / {
          add_header Access-Control-Allow-Origin *;
          add_header Access-Control-Allow-Methods GET;
          add_header Access-Control-Allow-Headers *;
          try_files \$$uri \$$uri/ =404;
        }
      }' > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.files.rule=Host(`files.ndomen.ru`)"
      - "traefik.http.routers.files.entrypoints=websecure"
      - "traefik.http.routers.files.tls.certresolver=mytlschallenge"
      - "traefik.http.services.files.loadbalancer.server.port=80"

networks:
  n8n_with_https_default:
    external: true